---
sap_hana_deployment_bundle_path: "/software/HANA_installation"
sap_hana_deployment_bundle_sar_file_name: "IMDB_SERVER20_051_0-80002031.SAR"
sap_hana_deployment_sapcar_path: "/software/SAPCAR"
sap_hana_deployment_sapcar_file_name: "SAPCAR.EXE"
sap_hana_deployment_root_password: "mysecretPassw0rd!"
sap_hana_deployment_sapadm_password: "mysecretPassw0rd!"
sap_hana_deployment_hana_sid: RHE
sap_hana_deployment_hana_instance_number: "00"
sap_hana_deployment_hana_env_type: development
sap_hana_deployment_hana_mem_restrict: "n"
sap_hana_deployment_common_master_password: "mysecretPassw0rd!"
sap_hana_deployment_sidadm_password: "mysecretPassw0rd!"
sap_hana_deployment_hana_db_system_password: "mysecretPassw0rd!"
sap_hana_deployment_ase_user_password: "mysecretPassw0rd!"
sap_hana_deployment_apply_license: false

sap_hana_hsr_hana_sid: RHE

sap_hana_hsr_hana_instance_number: "00"
sap_hana_hsr_hana_db_system_password: "mysecretPassw0rd!"
sap_hana_hsr_hana_primary_hostname: "{{ hostvars[groups['foreman_hana_image'][0]].ansible_hostname }}"

sap_hana_ha_pacemaker_hana_sid: RHE
sap_hana_ha_pacemaker_hana_instance_number: "00"
sap_hana_ha_pacemaker_vip: "172.16.4.250"
sap_hana_ha_pacemaker_hacluster_password: "mysecretPassw0rd!"
sap_hana_ha_pacemaker_node1_fqdn: "{{ hostvars[groups['foreman_hana_image'][0]].ansible_fqdn }}"
sap_hana_ha_pacemaker_node2_fqdn: "{{ hostvars[groups['foreman_hana_image'][1]].ansible_fqdn }}"
sap_hana_ha_pacemaker_node1_ip: "{{ hostvars[groups['foreman_hana_image'][0]].ansible_ssh_host }}"
sap_hana_ha_pacemaker_node2_ip: "{{ hostvars[groups['foreman_hana_image'][0]].ansible_ssh_host }}"
