---

- name: preconfigure all nodes
  hosts: all
 # hosts: "{{ vm_prefix }}*"

  roles:
    - sap-preconfigure

- name: preconfigure netweaver
  hosts: all
  #hosts: "{{ vm_prefix }}*:&foreman_s4_image"

  roles:
    - sap-netweaver-preconfigure

- name: preconfigure hana
  hosts: all
  #hosts: "{{ vm_prefix }}*:&foreman_hana_image"

  roles:
    - sap-hana-preconfigure
