---

- hosts: "{{ vm_prefix }}*"
  pre_tasks:
    - name: unregister from satellite
      redhat_subscription:
        state: absent

    - name: subscription-manager unregister
      command: subscription-manager unregister
      failed_when: false

    - name: subscription-manager clean
      command: subscription-manager clean
      failed_when: false

    - pause:
        seconds: 5

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "SAP S4 Server"
        org_id: Shadow_Man
        auto_attach: true
      failed_when: false
  roles:
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "hsr_role/alias: {{ sap_hana_hsr_role }} / {{ sap_hana_hsr_alias }}"

    - name: unregister from satellite
      redhat_subscription:
        state: absent

    - name: subscription-manager unregister
      command: subscription-manager unregister
      failed_when: false

    - name: subscription-manager clean
      command: subscription-manager clean
      failed_when: false

    - pause:
        seconds: 5

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "SAP S4 Server"
        org_id: Shadow_Man
        auto_attach: true
      failed_when: false
  roles:
    - redhat_sap.sap_hana_deployment
    - redhat_sap.sap_hana_hsr
#    - redhat_sap.sap_hana_ha_pacemaker

  post_tasks:
    - name: prevent transaction log to fill up disk
      shell: >
        /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
        -n {{ ansible_hostname }} -i {{ sap_hana_deployment_hana_instance_number }}
        -u SYSTEM -p {{ sap_hana_deployment_hana_db_system_password }}
        "ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'overwrite' WITH RECONFIGURE";
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: db_overwrite_cmd
      failed_when: false
      when: sap_hana_hsr_role == 'primary'

    - debug:
        msg: "{{ db_overwrite_cmd }}"

- hosts: "{{ vm_prefix }}*:&*s4_image"
  pre_tasks:
    - name: unregister from satellite
      redhat_subscription:
        state: absent

    - name: subscription-manager unregister
      command: subscription-manager unregister
      failed_when: false

    - name: subscription-manager clean
      command: subscription-manager clean
      failed_when: false

    - pause:
        seconds: 5

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "SAP S4 Server"
        org_id: Shadow_Man
        auto_attach: true
      failed_when: false
  roles:
    - sap_s4hana_deployment

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "hsr_role/alias: {{ sap_hana_hsr_role }} / {{ sap_hana_hsr_alias }}"

    # This is only temporarily needed until registration issues are resolved
    - name: unregister from satellite
      redhat_subscription:
        state: absent

    - name: subscription-manager unregister
      command: subscription-manager unregister
      failed_when: false

    - name: subscription-manager clean
      command: subscription-manager clean
      failed_when: false

    - pause:
        seconds: 5

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "SAP HANA Server"
        org_id: Shadow_Man
        auto_attach: true
      failed_when: false
  roles:
    - redhat_sap.sap_hana_ha_pacemaker