---

- hosts: "{{ vm_prefix }}*"
  roles:
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "{{ sap_hana_hsr_role }} - {{ sap_hana_hsr_alias }}"
  roles:
    - redhat_sap.sap_hana_deployment
    - redhat_sap.sap_hana_hsr
    - redhat_sap.sap_hana_ha_pacemaker

- hosts: "{{ vm_prefix }}*:&*s4_image"
  roles:
    - redhat_sap.sap_s4hana_deployment