---

- hosts: "{{ vm_prefix }}*:&*s4_image"
  # This is only temporarily needed until registration issues are resolved
  pre_tasks:
    - name: unregister from satellite
      redhat_subscription:
        state: absent

    - pause:
        seconds: 5

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "SAP S4 Server"
        org_id: Shadow_Man
        auto_attach: true
      failed_when: false

  roles:
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent
    - sap_s4hana_deployment