---

- name: Set up VM
  hosts: "{{ vm_prefix }}*"
  vars:
    software_repo_nfs_server: localhost
    software_repo_path: /var/lib/exports/software
    local_repo_path: /software
    activation_keys:
      S4_Image: SAP S4 Server
      HANA_Image: SAP HANA Server

  tasks:
#    - name: Subscribe to our Satellite using our activation key
#      redhat_subscription:
#        state: present
#        activationkey: "{{ activation_keys[foreman.hostgroup_name] | default('SAP HANA Server') }}"
#        org_id: Shadow_Man
#        auto_attach: true
#      failed_when: false
#
#    # this shouldn't be needed normally but auto-attach doesn't seem to always work
#    - name: attach susbscription
#      command: subscription-manager attach
#      failed_when: false
#
#    - name: unset role and usage
#      command: "{{ item }}"
#      failed_when: false
#      loop:
#        - syspurpose unset role
#        - syspurpose unset usage

    - name: check subscription status
      command: subscription-manager status
      register: sat_sub_status
      failed_when: false

    - name: output subscription status
      debug:
        msg: "{{ sat_sub_status }}"

    - name: build hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ hostvars[item].ansible_hostname }}"
        state: present
      when: hostvars[item].ansible_default_ipv4.address is defined
      loop: "{{ play_hosts }}"

    - name: ensure software repo directory exists
      file:
        path: "{{ local_repo_path }}"
        state: directory

    - name: ensure nfs utils are present
      package:
        name:
          - nfs-utils
          - nfs4-acl-tools

    - name: ensure software repo is mounted
      mount:
        path: "{{ local_repo_path }}"
        src: "{{ software_repo_nfs_server }}:/{{ software_repo_path }}"
        fstype: nfs
        opts: rw,_netdev
        state: mounted