- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_prefix: lab1vm

  tasks:
    - block:
        - name: Obtain SSO token with using username/password credentials
          ovirt_auth:
            insecure: yes

        - name: find snapshots
          ovirt_snapshot_info:
            vm: "{{ vm_prefix + '%02d'|format(1+(item|int)) }}*"
            description: sap_installed
          register: find_snapshots
          loop: "{{ range(0, 2 + 1, 1)|list }}"

        - debug:
            msg: "{{ find_snapshots.results }}"

        - name: stop vms
          ovirt_vm:
            name: "{{ item.ovirt_snapshots[0].vm.name }}"
            state: stopped
          loop: "{{ find_snapshots.results }}"

        - name: restore snapshots
          ovirt_snapshot:
            vm_name: "{{ item.ovirt_snapshots[0].vm.name }}"
            snapshot_id: "{{ item.ovirt_snapshots[0].id }}"
            state: restore
          loop: "{{ find_snapshots.results }}"

        - name: start vms
          ovirt_vm:
            name: "{{ item.ovirt_snapshots[0].vm.name }}"
            state: running
          loop: "{{ find_snapshots.results }}"

      always:
        - name: revoke the SSO token
          ovirt_auth:
            insecure: yes
            ovirt_auth: "{{ ovirt_auth }}"
            state: absent