---

- hosts: "{{ vm_prefix }}*"
  any_errors_fatal: true

  pre_tasks:
    - name: test whoami
      command: whoami
      become: yes
      become_user: "{{ sap_hana_hsr_hana_sid | lower }}adm"
      become_method: su
      register: whoami

    - debug:
        msg: "{{ whoami }}"

#  roles:
#    - sap_hana_hsr