---

- name: Set up HA for HANA
  hosts: "{{ vm_prefix }}*:&foreman_hana_image"

  roles:
    - role: ondrejhome.ha-cluster-pacemaker
      cluster_name: 'test-cluster'
      cluster_firewall: true
      cluster_configure_fence_xvm: false