---

- hosts: hanas

  vars:
    storage_pools:
      - name: sap
        disks:
          - nvme0n1
          #- xvdf
        volumes:
          - name: data
            size: "500 GiB"
            mount_point: "/hana/data"
            fs_type: xfs
            state: present
          - name: log
            size: "256 GiB"
            mount_point: "/hana/log"
            fs_type: xfs
            state: present
          - name: shared
            size: " 128 GiB"
            mount_point: "/hana/shared"
            fs_type: xfs
            state: present
          - name: sap
            size: "128 GiB"
            mount_point: "/usr/sap"
            state: present

  roles:
    - rhel-system-roles.storage
