---

- name: Set up VM
  hosts: "{{ vm_prefix }}*"
  vars:
    activation_keys:
      S4_Image: SAP S4 Server
      HANA_Image: SAP HANA Server

  pre_tasks:

    - block:
        - name: ensure hostname is set
          hostname:
            name: "{{ inventory_hostname_short }}"

        - name: gather new facts and hostname
          setup:
      when: ansible_hostname not in inventory_hostname

    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_keys[foreman.hostgroup_name] | default('SAP HANA Server') }}"
        org_id: Shadow_Man
        auto_attach: true

    - name: unset role and usage
      command: "{{ item }}"
      failed_when: false
      loop:
        - syspurpose unset role
        - syspurpose unset usage
        - syspurpose unset-sla

    - name: check subscription status
      command: subscription-manager status
      register: sat_sub_status
      failed_when: false

    - name: output subscription status
      debug:
        msg: "{{ sat_sub_status }}"

  roles:
    - common