- name: verify SAP working with HANA backend
  hosts: "{{ vm_prefix }}*:&*s4_image"

  vars:
    application_url: http://127.0.0.1:5000
    verify_task_timeout: 30

  tasks:
#    - name: exit when no connection
#      uri:
#        url: '{{ application_url }}/getall'
#        return_content: yes
#        validate_certs: no
#      become: no
#      register: response
#      until: response.content is undefined or response.status != 200
#      retries: "{{ verify_task_timeout | default(900) }}"
#      delay: 1
#      failed_when: false

    - name: exit when no connection
      shell: >
        /usr/sap/{{ sap_s4hana_deployment_db_sid }}/hdbclient/hdbsql -n {{ sap_s4hana_deployment_db_host }} -i {{ sap_s4hana_deployment_hana_instance_nr }}
        -u SYSTEM -p {{ sap_s4hana_deployment_master_password }}
        -dSystemDB "SELECT count(*) from sys.users"
      become: yes
      become_user: "{{ sap_s4hana_deployment_db_sid | lower }}adm"
      become_method: su
      register: response
      until: response.stdout is undefined or ('failed' in response.stderr)
      retries: "{{ verify_task_timeout | default(900) }}"
      delay: 1
      failed_when: false

    - debug:
        msg: "{{ response.stdout }}"

    - name: connection is available to db
      debug:
        msg: "connection to db is available"
      #when: response.status == 200
      when: ('selected' in response.stdout)

    - name: connection is not available to db
      fail:
        msg: "connection to db is not available"
      #when: response.status != 200
      when: ('failed' in response.stderr)