- name: wait for ip to be available
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    domain_name: example.com
    num_of_vms: 3

  tasks:
    - block:
        - name: obtain SSO token with using username/password credentials
          ovirt_auth:
            url: "{{ lookup('env', 'OVIRT_URL')|default(ovirt.url) }}"
            username: "{{ lookup('env', 'OVIRT_USERNAME')|default(ovirt.username) }}"
            password: "{{ lookup('env', 'OVIRT_PASSWORD')|default(ovirt.password) }}"
            insecure: yes

        - name: Check if VM has agent installed for Linux
          ovirt_vm_info:
            auth: "{{ ovirt_auth }}"
            pattern: name="{{ vm_prefix + '%02d'|format(vm|int) }}.{{ domain_name }}"
          register: result
          until: result.ovirt_vms | length == 0 or result.ovirt_vms[0].guest_operating_system.kernel.version.build | default(None) != None
          failed_when: result.ovirt_vms | length == 0
          retries: 60
          delay: 10
          loop: "{{ range(1, num_of_vms + 1, 1)|list }}"
          loop_control:
            loop_var: vm

      always:
        - name: revoke the SSO token
          ovirt_auth:
            url: "{{ lookup('env', 'OVIRT_URL')|default(ovirt.url) }}"
            username: "{{ lookup('env', 'OVIRT_USERNAME')|default(ovirt.username) }}"
            password: "{{ lookup('env', 'OVIRT_PASSWORD')|default(ovirt.password) }}"
            insecure: yes
            ovirt_auth: "{{ ovirt_auth }}"
            state: absent